apiVersion: v1
kind: Service
metadata:
  name: service
  namespace: dunand-mathieu
spec:
  selector:
    app: consumer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000 # Port exposé par le container Consumer
