apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: dunand-mathieu
  labels:
    app: frontend
    soft: nginx
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80 # Port exposé par le container Frontend
  type: ClusterIP