apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: dunand-mathieu
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000 # Port exposé par le container Frontend
