
services:
  rabbitmq:
    image: rabbitmq:3.13-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - rabbit_mqdata:/usr/share/rabbitmq/data

  backend:
    build: ./application/backend
    container_name: backend
    ports:
      - "5000:5000"
    depends_on:
      - rabbitmq
      - redis
    environment:
      - REDIS_HOST=redis
      - RABBITMQ_HOST=rabbitmq
      

  frontend:
    build: ./application/frontend
    container_name: frontend
    ports:
      - "3000:3000"

  consumer:
    build: ./application/consumer
    container_name: consumer
    depends_on:
      - rabbitmq
      - redis
    environment:
      - REDIS_HOST=redis
      - RABBITMQ_HOST=rabbitmq
    volumes:
      - ./consumer:/usr/src/app/consumer    

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"

volumes:
    rabbit_mqdata:
      driver: local