apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: redis-replicaset
  namespace: dunand-mathieu
spec:
  replicas: 3
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: redis:latest
          resources:
            requests:
              cpu: "4m"
              memory: "32Mi"
