apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: consumer
  namespace: dunand-mathieu
spec:
  replicas: 3
  selector:
    matchLabels:
      app: consumer
  template:
    metadata:
      labels:
        app: consumer
    spec:
      containers:
        - name: consumer
          image: virt-cc-ilia-mathieu-dunand-consumer:latest
          resources:
            requests:
              cpu: "4m"
              memory: "32Mi"
