apiVersion: v1
kind: Service
metadata:
  name: service
  namespace: dunand-mathieu
spec:
  selector:
    app: api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 4000 # Port exposé par le container API
