apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: api-replicaset
  namespace: dunand-mathieu
spec:
  replicas: 3
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: virt-cc-ilia-mathieu-dunand-backend:latest
          resources:
            requests:
              cpu: "4m"
              memory: "32Mi"
