apiVersion: v1
kind: Service
metadata:
  name: api-service
  namespace: dunand-mathieu
spec:
  selector:
    app: api
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000 # Port exposé par le container API
  type: ClusterIP 